services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "5000:5000"
    volumes:
      - ./models:/app/models
      - ./logs:/app/logs
    environment:
      - FLASK_ENV=${FLASK_ENV}
      - FLASK_ADDR=${FLASK_ADDR}
      - FLASK_PORT=${FLASK_PORT}
      - LOGS_ADDR=${LOGS_ADDR}
      - LOGS_PORT=${LOGS_PORT}
    depends_on:
      - logs
    networks:
      - app_net

  tests:
    build:
      context: .
      dockerfile: Dockerfile.tests
    environment:
      - FLASK_ADDR=${FLASK_ADDR}
      - FLASK_PORT=${FLASK_PORT}
    volumes:
      - ./logs:/app/logs
    depends_on:
      - app
    networks:
      - app_net

  logs:
    build:
      context: .
      dockerfile: Dockerfile.logs
    volumes:
      - logs:/fluentd/log
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      - app_net

networks:
  app_net:

volumes:
  logs:
