# Utilizar una imagen base de Python
FROM python:3.9-slim

# Establecer el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiar los archivos necesarios para ejecutar los tests
COPY requirements-tests.txt /app/
RUN pip install --no-cache-dir -r requirements-tests.txt
RUN apt-get update && apt-get install -y --no-install-recommends curl && rm -rf /var/lib/apt/lists/*

COPY test_app-desacoplado.py /app/

COPY wait-for-app.sh /app/
RUN chmod +x /app/wait-for-app.sh


# Ejecutar los tests cuando el host esté disponible
CMD ["./wait-for-app.sh", "http://app:5000", "pytest"]
