services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "5000:5000"
    volumes:
      - ./models:/app/models
      - ./logs:/app/logs
    environment:
      - FLASK_ENV=production
    depends_on:
      - logs
    networks:
      - app_net

  tests:
    build:
      context: .
      dockerfile: Dockerfile.tests
    volumes:
      - ./logs:/app/logs
    depends_on:
      - app
    networks:
      - app_net

  logs:
    build:
      context: .
      dockerfile: Dockerfile.logs
    volumes:
      - ./logs:/fluentd/log
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      - app_net

  db:
    image: mysql:8.0
    container_name: app_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: app_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
    networks:
      - app_net
    volumes:
      - db_data:/var/lib/mysql

networks:
  app_net:

volumes:
  db_data:
