name: Python Pytest

on: [push]

permissions:
  contents: read

jobs:
  deploy-and-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt upgrade -y
        python -m pip install --upgrade pip
        pip install keras
        pip install tensorflow
        pip install flask
        pip install pillow
        pip install pytest
        sudo apt install python3-pytest
    - name: Execute tests
      run: |
        pytest
